require('../api/controllers/user/user.test')
require('../api/controllers/project/project.test')
require('../api/controllers/job/job.test')
require('../api/controllers/notify/notify.test')
require('../api/controllers/comment/comment.test')
require('../api/controllers/team/team.test')